version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      electron-forge:
        patterns:
          - '@electron-forge/*'
      storybook:
        patterns:
          - '@storybook/*'
          - storybook
      webdriverio:
        patterns:
          - '@wdio/*'

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
